#!/usr/bin/env python3
"""Build script to embed HTML/CSS templates into a Python module.

This script reads template files from jinjatest/coverage/templates/
and generates jinjatest/coverage/_templates.py with string constants.

Usage:
    python scripts/build_templates.py

The generated _templates.py should be gitignored - regenerate before packaging.
"""

from pathlib import Path

TEMPLATES_DIR = Path(__file__).parent.parent / "jinjatest" / "coverage" / "templates"
OUTPUT_FILE = Path(__file__).parent.parent / "jinjatest" / "coverage" / "_templates.py"

HEADER = '''"""
Auto-generated template strings for HTML coverage reports.

DO NOT EDIT THIS FILE DIRECTLY.
Edit the source templates in jinjatest/coverage/templates/ and run:
    python scripts/build_templates.py
"""

'''


def escape_for_python(content: str) -> str:
    """Escape content for triple-quoted string."""
    # Replace backslashes first, then handle quotes
    content = content.replace("\\", "\\\\")
    # Escape triple quotes if present
    content = content.replace('"""', '\\"\\"\\"')
    return content


def main() -> None:
    """Read templates and generate Python module."""
    templates: dict[str, str] = {}

    for template_file in sorted(TEMPLATES_DIR.glob("*")):
        if template_file.is_file():
            name = template_file.stem.upper().replace("-", "_")
            ext = template_file.suffix.upper().lstrip(".")
            var_name = f"{name}_{ext}"
            content = template_file.read_text()
            templates[var_name] = content

    # Generate the Python module
    lines = [HEADER]

    for var_name, content in sorted(templates.items()):
        escaped = escape_for_python(content)
        lines.append(f'{var_name} = """{escaped}"""\n\n')

    OUTPUT_FILE.write_text("".join(lines))
    print(f"Generated {OUTPUT_FILE}")
    print(f"Templates embedded: {', '.join(sorted(templates.keys()))}")


if __name__ == "__main__":
    main()
