"""Hatch build hook to generate _templates.py before building."""

from hatchling.builders.hooks.plugin.interface import BuildHookInterface  # type: ignore[unresolved-import]


class TemplateBuildHook(BuildHookInterface):
    """Build hook that generates _templates.py from HTML/CSS sources."""

    PLUGIN_NAME = "template-builder"

    def initialize(self, version: str, build_data: dict) -> None:
        """Run template generation before build."""
        from pathlib import Path

        templates_dir = Path("jinjatest/coverage/templates")
        output_file = Path("jinjatest/coverage/_templates.py")

        if not templates_dir.exists():
            return

        header = '''"""
Auto-generated template strings for HTML coverage reports.

DO NOT EDIT THIS FILE DIRECTLY.
Edit the source templates in jinjatest/coverage/templates/ instead.
This file is generated automatically during the build process.
"""

'''

        templates: dict[str, str] = {}

        for template_file in sorted(templates_dir.glob("*")):
            if template_file.is_file():
                name = template_file.stem.upper().replace("-", "_")
                ext = template_file.suffix.upper().lstrip(".")
                var_name = f"{name}_{ext}"
                content = template_file.read_text()
                templates[var_name] = content

        lines = [header]

        for var_name, content in sorted(templates.items()):
            escaped = content.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
            lines.append(f'{var_name} = """{escaped}"""\n\n')

        output_file.write_text("".join(lines))

        if "force_include" not in build_data:
            build_data["force_include"] = {}
        build_data["force_include"][str(output_file)] = str(output_file)
